### ISSUE TITLE
[Meta] SDK Features Support Checklist

### ISSUE THREAD

**Issue by ldesgoui** [ldesgoui/discord_game_sdk#2]
# Core
- [x] Create (`GameSDK::new`/`GameSDK::with_create_flags`)
- [x] Destroy  (`GameSDK::drop`)
- [x] SetLogHook (forwards to `log` crate, opinionated)
- [x] RunCallbacks (`GameSDK::run_callbacks`)
- [x] GetXManager (internal only, opinionated)

# Activities
- [x] RegisterCommand
- [x] RegisterSteam
- [x] UpdateActivity
- [x] ClearActivity
- [x] SendRequestReply
- [x] SendInvite
- [x] AcceptInvite
- [x] OnActivityJoin
- [x] OnActivitySpectate
- [x] OnActivityJoinRequest
- [x] OnActivityInvite

# Applications
- [x] GetCurrentLocale
- [x] GetCurrentBranch
- [x] GetOAuth2Token
- [x] ValidateOrExit
- [x] GetTicket

# Images
- [x] Fetch
- [x] GetDimensions
- [x] GetData

# Lobbies
- [x] LobbyTransaction.SetType
- [x] LobbyTransaction.SetOwner
- [x] LobbyTransaction.SetCapacity
- [x] LobbyTransaction.SetMetadata
- [x] LobbyTransaction.DeleteMetadata
- [x] LobbyTransaction.SetLocked
- [x] LobbyMemberTransaction.SetMetadata
- [x] LobbyMemberTransaction.DeleteMetadata
- [x] LobbySearch.Filter
- [x] LobbySearch.Sort
- [x] LobbySearch.Limit
- [x] LobbySearch.Distance
- [x] GetLobbyCreateTransaction
- [x] GetLobbyUpdateTransaction
- [x] GetMemberUpdateTransaction
- [x] CreateLobby
- [x] UpdateLobby
- [x] DeleteLobby
- [x] ConnectLobby
- [x] ConnectLobbyWithActivitySecret
- [x] GetLobbyActivitySecret
- [x] DisconnectLobby
- [x] GetLobby
- [x] LobbyMetadataCount
- [x] GetLobbyMetadataKey
- [x] GetLobbyMetadataValue
- [x] MemberCount
- [x] GetMemberUserId
- [x] GetMemberUser
- [x] MemberMetadataCount
- [x] GetMemberMetadataKey
- [x] GetMemberMetadataValue
- [x] UpdateMember
- [x] SendLobbyMessage
- [x] GetSearchQuery
- [x] Search
- [x] LobbyCount
- [x] GetLobbyId
- [x] ConnectVoice
- [x] DisconnectVoice
- [x] OnLobbyUpdate
- [x] OnLobbyDelete
- [x] OnMemberConnect
- [x] OnMemberUpdate
- [x] OnMemberDisconnect
- [x] OnMessage
- [x] OnSpeaking
- [x] ConnectNetwork
- [x] DisconnectNetwork
- [x] FlushNetwork
- [x] OpenNetworkChannel
- [x] SendNetworkMessage
- [x] OnNetworkMessage

# Networking
- [x] GetPeerId
- [x] Flush
- [x] OpenChannel
- [x] OpenPeer
- [x] UpdatePeer
- [x] SendMessage
- [x] CloseChannel
- [x] ClosePeer
- [x] OnMessage
- [x] OnRouteUpdate

# Overlay
- [x] IsEnabled
- [x] IsLocked
- [x] SetLocked
- [x] OpenActivityInvite
- [x] OpenGuildInvite
- [x] OpenVoiceSettings
- [x] OnToggle

# Relationships
- [x] Filter
- [x] Get
- [x] GetAt
- [x] Count
- [x] OnRefresh
- [x] OnRelationshipUpdate

# Storage
- [x] GetPath
- [x] Read
- [x] ReadAsync
- [x] ReadAsyncPartial
- [x] Write
- [x] WriteAsync
- [x] Delete
- [x] Exists
- [x] Stat
- [x] Count
- [x] StatAt

# Store 
- [x] FetchSkus
- [x] CountSkus
- [x] GetSku
- [x] GetSkuAt
- [x] FetchEntitlements
- [x] CountEntitlements
- [x] GetEntitlement
- [x] GetEntitlementAt
- [x] HasSkuEntitlement
- [x] StartPurchase
- [x] OnEntitlementCreate
- [x] OnEntitlementDelete

# Users
- [x] GetCurrentUser
- [x] GetUser
- [x] GetCurrentUserPremiumType
- [ ] CurrentUserHasFlag
- [x] OnCurrentUserUpdate

# Voice
- [ ] GetInputMode
- [ ] SetInputMode
- [x] IsSelfMute
- [x] SetSelfMute
- [x] IsSelfDeaf
- [x] SetSelfDeaf
- [x] IsLocalMute
- [x] SetLocalMute
- [x] GetLocalVolume
- [x] SetLocalVolume
