### ISSUE TITLE
Release 1.0.0-rc.1 checklist

### ISSUE THREAD

**Issue by ldesgoui** [ldesgoui/discord_game_sdk#59]
- [x] doctests in `src/methods/storage.rs`
- [x] Verify all docs are proper
- [x] Document dynamic linking (#49) 
- [x] Fix Mac OSX CI Build (#58)
- [x] Write "changelog"
- [x] Check on projects using crate, offer a PR if fixes are easy
- [x] Publish `discord_game_sdk_sys` 1.0.0
- [x] Publish `discord_game_sdk` 1.0.0-rc.1
